export const IPC_CHANNELS = {
  analyzeGame: 'chess:analyze-game',
  analysisProgress: 'chess:analysis-progress',
  cancelAnalysis: 'chess:cancel-analysis',
  openPgnFile: 'chess:open-pgn-file',
  fetchChessComGames: 'chess:fetch-chesscom-games',
  fetchChessComStats: 'chess:fetch-chesscom-stats',
  getSettings: 'settings:get',
  setTheme: 'settings:set-theme',
  evaluatePosition: 'engine:evaluate-position',
  startAccountLink: 'account:start-link',
  verifyAccountLink: 'account:verify-link',
  disconnectAccount: 'account:disconnect',
  openChessComProfileSettings: 'app:open-chesscom-profile-settings',
  scanChessComGames: 'insights:scan',
  scanProgress: 'insights:scan-progress',
  cancelScan: 'insights:cancel-scan',
  getInsightsReport: 'insights:get-report',
  getMasteryTree: 'mastery:get-tree',
  getNodeQueue: 'mastery:get-node-queue',
  submitPuzzleReview: 'puzzles:submit-review',
  getPuzzleStats: 'puzzles:get-stats',
  submitPuzzleOutcome: 'puzzles:submit-outcome'
} as const
